version: "3.4"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_publicshare
    volumes:
      - /opt/publicfolder/:/static/public/sharefolder:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    expose:
      - 80
    networks:
      - pi
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.publicshare.loadBalancer.server.port=80"
      - "traefik.http.routers.publicshare.rule=PathPrefix(`/public`)"
      - "traefik.http.routers.publicshare.tls"
networks:
  pi:
    external: true
